import type { LucideIcon } from 'lucide-react-native';
import {
	ArrowRight,
	Banknote,
	BookOpen,
	Briefcase,
	Building,
	Calendar,
	Car,
	Cat,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronUp,
	Circle,
	Coffee,
	Coins,
	Cookie,
	CreditCard,
	Dog,
	Diamond,
	Dumbbell,
	Film,
	Gamepad,
	Gem,
	Gift,
	GraduationCap,
	Headphones,
	Heart,
	Home,
	Key,
	Laptop,
	Landmark,
	Lightbulb,
	Mic,
	Music,
	Palette,
	Pencil,
	Percent,
	PiggyBank,
	Pizza,
	Plane,
	Plus,
	Rocket,
	School,
	Shield,
	ShieldCheck,
	Shirt,
	ShoppingCart,
	Smartphone,
	Sofa,
	Star,
	Tag,
	Ticket,
	TrendingUp,
	Trash2,
	Tv,
	Umbrella,
	Utensils,
	UserCheck,
	Users,
	Wallet,
	Wifi,
	X,
	Zap,
	BottleWine,
	BriefcaseConveyorBelt,
	Bus,
	Cake,
	Camera,
	Cigarette,
	Globe,
	RefreshCw,
	TentTree,
	SoapDispenserDroplet,
	Baby,
} from 'lucide-react-native';

// Icon registry mapping kebab-case names to icon components
// This approach enables tree-shaking - only icons in this registry are bundled
export const iconRegistry: Record<string, LucideIcon> = {
	// Income icons
	briefcase: Briefcase,
	building: Building,
	gift: Gift,
	percent: Percent,
	'trending-up': TrendingUp,
	wallet: Wallet,

	// Account icons
	'credit-card': CreditCard,
	banknote: Banknote,
	landmark: Landmark,
	'piggy-bank': PiggyBank,
	coins: Coins,

	// Category and savings icons
	baby: Baby,
	book: BookOpen,
	'book-open': BookOpen,
	'bottle-wine': BottleWine,
	'briefcase-conveyor-belt': BriefcaseConveyorBelt,
	bus: Bus,
	cake: Cake,
	camera: Camera,
	car: Car,
	cat: Cat,
	cigarette: Cigarette,
	coffee: Coffee,
	cookie: Cookie,
	diamond: Diamond,
	dog: Dog,
	dumbbell: Dumbbell,
	film: Film,
	gamepad: Gamepad,
	gem: Gem,
	'graduation-cap': GraduationCap,
	globe: Globe,
	headphones: Headphones,
	heart: Heart,
	home: Home,
	key: Key,
	laptop: Laptop,
	lightbulb: Lightbulb,
	mic: Mic,
	music: Music,
	palette: Palette,
	pizza: Pizza,
	plane: Plane,
	rocket: Rocket,
	school: School,
	shield: Shield,
	'shield-check': ShieldCheck,
	shirt: Shirt,
	'shopping-cart': ShoppingCart,
	smartphone: Smartphone,
	sofa: Sofa,
	star: Star,
	tag: Tag,
	'tent-tree': TentTree,
	ticket: Ticket,
	tv: Tv,
	umbrella: Umbrella,
	'user-check': UserCheck,
	users: Users,
	utensils: Utensils,
	wifi: Wifi,
	zap: Zap,
	'soap-dispenser-droplet': SoapDispenserDroplet,

	// UI icons
	'chevron-left': ChevronLeft,
	'chevron-right': ChevronRight,
	'chevron-up': ChevronUp,
	'chevron-down': ChevronDown,
	plus: Plus,
	trash2: Trash2,
	'arrow-right': ArrowRight,
	calendar: Calendar,
	pencil: Pencil,
	x: X,
	circle: Circle,
	'refresh-cw': RefreshCw,
};

/**
 * Get icon component by kebab-case name
 * Falls back to Circle icon if not found
 */
export function getIcon(name: string): LucideIcon {
	return iconRegistry[name.toLowerCase()] || Circle;
}
